- name: install epel release
  yum:
    name: epel-release
    state: present

- name: update all packages
  yum:
    name: '*'
    state: latest

- name: install content
  yum:
    name:
      - nbdkit
      - nbdkit-basic-plugins
      - qemu-img
      - libguestfs-tools
    state: present
