- name: Conversion host content tasks
  block:
    - name: Reboot conversion host if required
      openstack.cloud.server_action:
        cloud: "{{ os_migrate_conversion_cloud }}"
        action: reboot
        server: "{{ os_migrate_conversion_host_name }}"
        wait: true
      when: os_migrate_conversion_host_reboot | default(true)

    - name: Wait for conversion host to be up
      wait_for:
        host: "{{ os_migrate_conversion_host_name }}"
        port: 22
        delay: 60
        timeout: 900
      when: os_migrate_conversion_host_reboot | default(true)

    - name: Display host os
      ansible.builtin.debug:
        msg: >-
          Conversion Host OS is
          {{ ansible_distribution }} {{ ansible_distribution_version }}

    - name: running pre content hook
      ansible.builtin.shell: "{{ os_migrate_conversion_host_pre_content_hook }}"
      args:
        executable: /bin/bash
      when: os_migrate_conversion_host_pre_content_hook is string

    - name: Include CentOS tasks
      ansible.builtin.include_tasks: centos.yml
      when: ansible_distribution in ['CentOS']

    - name: Include RHEL tasks
      ansible.builtin.include_tasks: rhel.yml
      when: ansible_distribution in ['RedHat']

    - name: running post content hook
      ansible.builtin.shell: "{{ os_migrate_conversion_host_post_content_hook }}"
      args:
        executable: /bin/bash
      when: os_migrate_conversion_host_post_content_hook is string
