- name: create os_migrate conversion net
  openstack.cloud.network:
    name: "{{ os_migrate_conversion_net_name }}"
    mtu: "{{ os_migrate_conversion_net_mtu }}"
    cloud: "{{ os_migrate_conversion_cloud }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

- name: debug suffix net_name vs network_name
  ansible.builtin.debug:
    msg: "{{ os_migrate_conversion_net_name }}"

- name: create os_migrate conversion subnet
  openstack.cloud.subnet:
    name: "{{ os_migrate_conversion_subnet_name }}"
    network_name: "{{ os_migrate_conversion_net_name }}"
    dns_nameservers: "{{ os_migrate_conversion_subnet_dns_nameservers }}"
    cidr: "{{ os_migrate_conversion_subnet_cidr }}"
    allocation_pool_start: "{{ os_migrate_conversion_subnet_alloc_start }}"
    allocation_pool_end: "{{ os_migrate_conversion_subnet_alloc_end }}"
    cloud: "{{ os_migrate_conversion_cloud }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

- name: Gather information about previously created networks
  openstack.cloud.networks_info:
    cloud: "{{ os_migrate_conversion_cloud }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"
  register: result

- name: Show openstack networks
  ansible.builtin.debug:
    msg: "{{ result.networks }}"

- name: Debug "No Network found for public" error
  ansible.builtin.debug:
    msg: "{{ os_migrate_conversion_external_network_name  }}"

- name: create os_migrate conversion router
  openstack.cloud.router:
    name: "{{ os_migrate_conversion_router_name }}"
    network: "{{ os_migrate_conversion_external_network_name }}"
    interfaces:
      - net: "{{ os_migrate_conversion_net_name }}"
        subnet: "{{ os_migrate_conversion_subnet_name }}"
        portip: "{{ os_migrate_conversion_router_ip }}"
    cloud: "{{ os_migrate_conversion_cloud }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"
