- name: scan available projects
  openstack.cloud.project_info:
    auth: "{{ os_migrate_src_auth }}"
    auth_type: "{{ os_migrate_src_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_src_region_name|default(omit) }}"
    validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_src_client_key|default(omit) }}"
  register: src_projects_info

- name: create id-name pairs of projects to export quotas for
  ansible.builtin.set_fact:
    export_projects_ids_names: "{{ (
      src_projects_info.openstack_projects
        | json_query('[*].{name: name, id: id}')
        | sort(attribute='id') ) }}"

- name: filter names of projects to export quotas for
  ansible.builtin.set_fact:
    export_projects_ids_names: "{{ (
      export_projects_ids_names
        | os_migrate.os_migrate.stringfilter(os_migrate_projects_filter,
                                             attribute='name') ) }}"

- name: export quotas of a project
  ansible.builtin.include_tasks: export_single_project_quotas.yml
  loop: "{{ export_projects_ids_names }}"
  loop_control:
    loop_var: export_project
